name: Download S3 with endpoint support
description: GitHub action to download files from S3
author: Allen
inputs:
  aws_access_key_id:
    description: AWS access key ID.
    required: true
  aws_secret_access_key:
    description: AWS secret access key.
    required: true
  aws_region:
    description: The region to send service requests to.
    required: true
  aws_bucket:
    description: The bucket name containing the files to download.
    required: true
  endpoint:
    description: S3 endpoint URL.
    required: false
  source:
    description: The directory (or file path) on the bucket to which you want to download.
    required: false
    default: ''
  target:
    description: The local directory (or file path) where files are saved.
    required: false
    default: '.'
outputs:
  succeeded:
    description: Number of successful files
  failed:
    description: Number of failed files
runs:
  using: node20
  main: action/index.js
branding:
  icon: download-cloud
  color: red
